### ISSUE TITLE
WIP ブランチを分ける

### ISSUE THREAD

**Issue by waxsd100** [TUSB/TheUnusualSkyBlock#1]
制作サーバとリポジトリ同期後、レシピ関連のエラーや他の人のコミットした内容のエラーがそのまますべて列挙され、差し戻しなどが必要となり、非常に制作しづらい状況となっている。
また、膨大な量のレシピによりリロード時間が10秒と大幅にかかってしまう。

そのため、今現在の環境では誰一人エラーを出さないようにコミットをし、レシピなどの大量のファイルを削除してからローカル開発しなければならない状況となっており、Gitの特徴を活かしきれず、このままだと検証や開発の場としてもふさわしくないため
コマンド、レシピ、演出、等目的別に合わせたブランチ管理が必要。

**Comment by waxsd100** [comment]
```

赤石愛今日 午後9時24分
コマンドと演出は一緒のほうが
wAx_100今日 午後9時32分
うーんちょっと迷う　例えば負荷とかそこら辺見るときは分けてあったほうが楽じゃないかなとか

うーーん演出側のエラーかシステム側のエラーかって見るとき分けてあったほうが(編集済)
いやログでわかるか
クマコンドリア@らめええ！௵出ちゃいまひゅううう！！今日 午後9時33分
そもそも一緒のfunctionに入れてるはずだしなぁ
wAx_100今日 午後9時33分
あれ一緒だったの分けているのかと思った
赤石愛今日 午後9時34分
私が作ったのを演出班が編集って感じだからファイル一緒
モブとかアイテムとかレシピとかは別
```

master
　│
stage
　├ recipe
　├ command
　└ entity


performance を削除しstageの下位ブランチを4つから3つへ変更

**Comment by waxsd100** [comment]
@tatuharu レビュー is おねがい

**Comment by waxsd100** [comment]
ブランチに
advancement 進捗用
achievement 実績用
を追加

略称英語があればそっちを使用したい...

**Comment by waxsd100** [comment]
全く一緒だったのでブランチモデルの修正

```
master
　│
stage
　├ recipe
　├ command
　├ entity
　├ advancement
　└ quest
```

**Comment by waxsd100** [comment]
### **わけるぅぅぅぅ！！！！！**

**Comment by waxsd100** [comment]
**あけましておめでとうございます。**
気が向いたらわけます。

**Comment by wakame0731** [comment]
**明けましておめでとうございます。**
よろしくお願いします。

**Comment by waxsd100** [comment]
赤石さん案を元に進めたいです。

ブランチを分けると言って気がついたら性癖が変わっていた

**Comment by waxsd100** [comment]
○西暦
✕性癖

**Comment by waxsd100** [comment]
普通に考えてもうすでに最初から別れているんだから無理にブランチで分けなくても良くねってなったので却下

てか製作中にVerが変わっったら破綻する...
