### ISSUE TITLE
v13αにおいて最大スポナー数と破壊数をログに表示したい。

### ISSUE THREAD

**Issue by anminmakura** [TUSB/TheUnusualSkyBlock#108]
### アイデアのカテゴリー

インターフェイス全般

### アイデア概要

スポナーを破壊する毎に以下のログが流れるようにする。

◆スポナーを破壊した！
【破壊数/現在数】3/78

または、ステータスメニューで破壊数の確認を行えるようにする。

【破壊数/現在数】3/78

### 使用するシステム

スポナーカウント
または
ステータスメニュー

**Comment by NePonpon** [comment]
* 達成率実装、Alphaモブ更新
aef7e07ab4133a761d3466396f106678a888a6db
