### ISSUE TITLE
TODO 1.16用ブランチを作成

### ISSUE THREAD

**Issue by waxsd100** [TUSB/TheUnusualSkyBlock#11]
現在のDevと1.14ブランチを1.16ブランチに結合
ついでに今後はファイルヘッダーをつけて個別にどのVerのときに書いたかをわかるようにしたい

**Comment by waxsd100** [comment]
1.13用(dev)ブランチの中に1.14のコードが入って混ざっている可能性。

とりあえず 1.14用ブランチにあるのを優先的に結合

**Comment by NePonpon** [comment]
すでに1-17-1ブランチも作成されていて古いissueなのでclose
