### ISSUE TITLE
[バグ] 特殊デバフが付与された際にログにデバフの内容が表示されない

### ISSUE THREAD

**Issue by anminmakura** [TUSB/TheUnusualSkyBlock#114]
### 概要

特殊デバフが付与された際にログにデバフの内容が表示されない。
またその際に別の特殊デバフが付与された際に先に付与された特殊デバフが起動する。
特殊デバフトントにおいてはログが出ないが、起動はしているという謎のめいたことになっており
トントが起動してもトントの特殊デバフが消えることがなかった。

解除用のeffectは動いているのか、一応各特殊デバフ解除用エフェクト
死の宣告3カウント、10カウント、やけど、凍結、麻痺、混乱、呪詛、病気、トントを試したが正常に動作している。

### 再現方法

1.特殊デバフを受けた際ログに表示されない
2.その際に異なる特殊デバフを続けるか、解除用のバフを受けることでログが表示される。
またこの時かかっていたデバフが正常に動く。

**Comment by NePonpon** [comment]
修正案  
透明化advancementsのrevokeを1tickずらしてみる

**Comment by NePonpon** [comment]
死の宣告解除(Amplifier:71)でのみこのバグが起こることを確認。

**Comment by NePonpon** [comment]
処理を1tickずらすとバグが起きなくなった
