### ISSUE TITLE
[バグ] 鉄のツルハシ＋謎の刻印Ⅰでエンチャントがつかない

### ISSUE THREAD

**Issue by NePonpon** [TUSB/TheUnusualSkyBlock#116]
### 概要

鉄のツルハシに謎の魔石Ⅰを付与したところ、画像のようにエンチャントエフェクトだけで実際についていないアイテムが手に入った。

![image](https://user-images.githubusercontent.com/62683212/177005248-ba5f0d40-646d-447b-810e-e878871e8a29.png)

マルチプレイで発見。

シングルプレイで再現するときに、一回目だけエンチャントが付与されたが、二回目以降はこのバグが発生して付与されなくなった。

### 再現方法

1. エンチャント台を開く
2. 鉄のツルハシと謎の魔石を配置する
3. エンチャントテーブルを取り、エンチャントする

### 予想される動作

なんらかのエンチャントが付与される。

### NBTデータ

対象のアイテムを持った状態で以下を取得

```mcfunction
data get entity @s SelectedItem.tag.display.Lore
#-> []
```

```mcfunction
data get entity @s SelectedItem.tag.Enchantments
#-> [{id:"tusb:エンチャント済み"}]
```

**Comment by Irohamaru** [comment]
[[cfbeed3](https://github.com/TUSB/TheUnusualSkyBlock/commit/cfbeed33d7ded26e3e03f7e54d0c57b246835127) エンチャントが付与されないケースを修正 - Irohamaru
](https://github.com/TUSB/TheUnusualSkyBlock/commit/cfbeed33d7ded26e3e03f7e54d0c57b246835127)
