### ISSUE TITLE
スキルの攻撃属性の情報を開示する

### ISSUE THREAD

**Issue by NePonpon** [TUSB/TheUnusualSkyBlock#119]
### アイデアのカテゴリー

職業スキル

### アイデア概要

プレイヤーのスキルに設定されている攻撃の属性がわからない。
どの属性で攻撃できるかわかるようにしたい。

> 安眠まくら(-ヮ-)
プレイヤーのスキル攻撃さ
何がどの属性って正直わからなくない？
何かわかるようにできないかなぁこれ今後

**Comment by anminmakura** [comment]
現状の魔石とスキルと属性についての問題

現状Playerは以下の情報の欠落により
プレイ時に魔石の真価について気づく事はない。

スキルがどの属性かを明記しておらず、
属性ブースター系の魔石を活かすことが情報を知っている製作者ですら難しい。
また刻印付与したとしても数値が見えないので攻撃力の差の変化に
初見では気づけず、
MOBがダメージを与えた時のリアクションが乏しいので
ちゃんと効いているのか不安に駆られる。

その為アナライズやライブラを使って看破していくプレイスタイルを製作者は望んでいるが、
別の問題ではあるが補足として以下２点により、そのプレイスタイルを困難にしている。

１、アナライズ、ライブラは視線の中心にいるMOBの情報を見るスキルである為に
トゲイガーのように錯乱する動きをするMOBに当てることが難しい。

２、戦闘中は画面の中心を見ることに集中してしまう為、情報を見ている余裕がない。

感想として目まぐるしい戦闘において解析は困難を極めるので、システム担当者は
そのうちこれらをどうにかしてほしい。

提案としてはやはりダメージを受けた際のリアクションを追加し、
またそのリアクションに意味を持たせたほうが良い。

職業スキルで解決していく手動スタイルにも限度があるので
数値を出すなり、HPバーを出すなりしないと戦闘においての情報量をPlayerは情報理解度を深めることが出来ず
適当な攻撃のみが飛び交う戦場と化してしまう。
序場はそれで良いかもしれないが、後半もそれではただのごり押しになるので
今後の課題としてこの辺りを修正すべき。

v13α中はいわゆる実験環境であるので、既存の良くない部分は壊していって良いと思っているので
改善できる点は改善していってほしい。

**Comment by NePonpon** [comment]
61df3ee77c3985412ef437cef011c47b2b9c8238
