### ISSUE TITLE
[バグ] 合成の手引きのテキストを修正する

### ISSUE THREAD

**Issue by NePonpon** [TUSB/TheUnusualSkyBlock#125]
### 発生したTUSBv13のVersion

v13.0.0α

### 概要

loot_tableのために、`\\n`を`\\\\n`にしていたところ、村人から手に入るアイテムでは`\\n`が対応しているため、書式が崩れる。

![image](https://user-images.githubusercontent.com/62683212/183289321-84b1a464-fbaa-466a-aa64-0c63fa81be4b.png)

### 再現方法

1. 野生の魔石商人を見つける
2. 合成の手引きを購入する
3. 中身を見る

### 予想される動作

![image](https://user-images.githubusercontent.com/62683212/183289337-aa662260-efb9-47d2-b687-70c326312222.png)

### 原因となるコマンド

```mcfunction
give @p minecraft:written_book{title:"合成の手引き",author:"魔商・ラズリ―",generation:1,resolved:false,pages:['["\\\\n\\\\n\\\\n\\\\n\\\\n\\\\n",{"translate":"     合成の手引き","color":"gold","bold":true},"\\\\n",{"translate":"     ～魔石の可能性～","italic":true}]','["",{"translate":"目にする多くの魔石には%1$sが付いている。","with":[{"translate":"１つのエンチャント","color":"blue","bold":true}]},"\\\\n",{"translate":"しかし%1$sが付いた魔石も存在する。","with":[{"translate":"複数のエンチャント","color":"red","bold":true}]},"\\\\n\\\\n",{"translate":"これは魔石同士を%1$sで合成することで作成できるのだ。","with":[{"translate":"block.minecraft.anvil","bold":true}]}]','["\\\\n",{"translate":"       =========\\\\n       合成のルール\\\\n       ========="},"\\\\n\\\\n",{"translate":"・決められた４つのスロットに魔石を配置する。"},"\\\\n",{"translate":"・正しく魔石を配置する。"},"\\\\n",{"translate":"・同じTier同士でのみ合成ができる。"},"\\\\n",{"translate":"(Tier：Ⅰ、Ⅱなどのエンチャントレベル)"}]','["",{"translate":"         - 目次 -\\\\n"},{"translate":"クリックすることでページ移動ができます。","italic":true},"\\\\n\\\\n",{"translate":"・魔石のTier強化","clickEvent":{"action":"change_page","value":"5"}},"\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"元素の"}],"clickEvent":{"action":"change_page","value":"6"}},"\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"陰陽の"}],"clickEvent":{"action":"change_page","value":"7"}},"\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"賢者の"}],"clickEvent":{"action":"change_page","value":"8"}},"\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"純化の"}],"clickEvent":{"action":"change_page","value":"9"}},"\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"進化の"}],"clickEvent":{"action":"change_page","value":"10"}},"\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"竜鱗の"}],"clickEvent":{"action":"change_page","value":"11"}},"\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"精霊の"}],"clickEvent":{"action":"change_page","value":"12"}},"\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"神威の"}],"clickEvent":{"action":"change_page","value":"13"}},"\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"神秘の"}],"clickEvent":{"action":"change_page","value":"14"}}]','["",{"translate":"・魔石のTier強化"},"\\\\n\\\\n",{"translate":"- 必要な魔石"},"\\\\n\\\\n",{"translate":"同じ名前、同じTierの魔石 ×４"}]','["",{"translate":"・%1$s魔石","with":[{"translate":"元素の"}]},"\\\\n\\\\n",{"translate":"- 必要な魔石"},"\\\\n\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"炎の"}]},"\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"氷の"}]},"\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"雷の"}]}]','["",{"translate":"・%1$s魔石","with":[{"translate":"陰陽の"}]},"\\\\n\\\\n",{"translate":"- 必要な魔石"},"\\\\n\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"光の"}]},"\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"闇の"}]}]','["",{"translate":"・%1$s魔石","with":[{"translate":"賢者の"}]},"\\\\n\\\\n",{"translate":"- 必要な魔石"},"\\\\n\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"炎威の"}]},"\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"氷威の"}]},"\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"雷威の"}]}]','["",{"translate":"・%1$s魔石","with":[{"translate":"純化の"}]},"\\\\n\\\\n",{"translate":"- 必要な魔石"},"\\\\n\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"光威の"}]},"\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"闇威の"}]}]','["",{"translate":"・%1$s魔石","with":[{"translate":"進化の"}]},"\\\\n\\\\n",{"translate":"- 必要な魔石"},"\\\\n\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"生命の"}]},"\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"魔力の"}]}]','["",{"translate":"・%1$s魔石","with":[{"translate":"竜鱗の"}]},"\\\\n\\\\n",{"translate":"- 必要な魔石"},"\\\\n\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"防護の"}]},"\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"大盾の"}]},"\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"耐爆の"}]},"\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"耐火の"}]}]','["",{"translate":"・%1$s魔石","with":[{"translate":"精霊の"}]},"\\\\n\\\\n",{"translate":"- 必要な魔石"},"\\\\n\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"元素の"}]},"\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"陰陽の"}]}]','["",{"translate":"・%1$s魔石","with":[{"translate":"神威の"}]},"\\\\n\\\\n",{"translate":"- 必要な魔石"},"\\\\n\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"賢者の"}]},"\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"純化の"}]}]','["",{"translate":"・%1$s魔石","with":[{"translate":"神秘の"}]},"\\\\n\\\\n",{"translate":"- 必要な魔石"},"\\\\n\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"精霊の"}]},"\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"神威の"}]}]'],display:{Name:'{"translate":"合成の手引き","bold":true,"color":"yellow"}'}}
```

### NBTデータ

{title:"合成の手引き",author:"魔商・ラズリ―",generation:1,resolved:false,pages:['["\\\\n\\\\n\\\\n\\\\n\\\\n\\\\n",{"translate":"     合成の手引き","color":"gold","bold":true},"\\\\n",{"translate":"     ～魔石の可能性～","italic":true}]','["",{"translate":"目にする多くの魔石には%1$sが付いている。","with":[{"translate":"１つのエンチャント","color":"blue","bold":true}]},"\\\\n",{"translate":"しかし%1$sが付いた魔石も存在する。","with":[{"translate":"複数のエンチャント","color":"red","bold":true}]},"\\\\n\\\\n",{"translate":"これは魔石同士を%1$sで合成することで作成できるのだ。","with":[{"translate":"block.minecraft.anvil","bold":true}]}]','["\\\\n",{"translate":"       =========\\\\n       合成のルール\\\\n       ========="},"\\\\n\\\\n",{"translate":"・決められた４つのスロットに魔石を配置する。"},"\\\\n",{"translate":"・正しく魔石を配置する。"},"\\\\n",{"translate":"・同じTier同士でのみ合成ができる。"},"\\\\n",{"translate":"(Tier：Ⅰ、Ⅱなどのエンチャントレベル)"}]','["",{"translate":"         - 目次 -\\\\n"},{"translate":"クリックすることでページ移動ができます。","italic":true},"\\\\n\\\\n",{"translate":"・魔石のTier強化","clickEvent":{"action":"change_page","value":"5"}},"\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"元素の"}],"clickEvent":{"action":"change_page","value":"6"}},"\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"陰陽の"}],"clickEvent":{"action":"change_page","value":"7"}},"\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"賢者の"}],"clickEvent":{"action":"change_page","value":"8"}},"\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"純化の"}],"clickEvent":{"action":"change_page","value":"9"}},"\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"進化の"}],"clickEvent":{"action":"change_page","value":"10"}},"\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"竜鱗の"}],"clickEvent":{"action":"change_page","value":"11"}},"\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"精霊の"}],"clickEvent":{"action":"change_page","value":"12"}},"\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"神威の"}],"clickEvent":{"action":"change_page","value":"13"}},"\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"神秘の"}],"clickEvent":{"action":"change_page","value":"14"}}]','["",{"translate":"・魔石のTier強化"},"\\\\n\\\\n",{"translate":"- 必要な魔石"},"\\\\n\\\\n",{"translate":"同じ名前、同じTierの魔石 ×４"}]','["",{"translate":"・%1$s魔石","with":[{"translate":"元素の"}]},"\\\\n\\\\n",{"translate":"- 必要な魔石"},"\\\\n\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"炎の"}]},"\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"氷の"}]},"\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"雷の"}]}]','["",{"translate":"・%1$s魔石","with":[{"translate":"陰陽の"}]},"\\\\n\\\\n",{"translate":"- 必要な魔石"},"\\\\n\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"光の"}]},"\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"闇の"}]}]','["",{"translate":"・%1$s魔石","with":[{"translate":"賢者の"}]},"\\\\n\\\\n",{"translate":"- 必要な魔石"},"\\\\n\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"炎威の"}]},"\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"氷威の"}]},"\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"雷威の"}]}]','["",{"translate":"・%1$s魔石","with":[{"translate":"純化の"}]},"\\\\n\\\\n",{"translate":"- 必要な魔石"},"\\\\n\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"光威の"}]},"\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"闇威の"}]}]','["",{"translate":"・%1$s魔石","with":[{"translate":"進化の"}]},"\\\\n\\\\n",{"translate":"- 必要な魔石"},"\\\\n\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"生命の"}]},"\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"魔力の"}]}]','["",{"translate":"・%1$s魔石","with":[{"translate":"竜鱗の"}]},"\\\\n\\\\n",{"translate":"- 必要な魔石"},"\\\\n\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"防護の"}]},"\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"大盾の"}]},"\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"耐爆の"}]},"\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"耐火の"}]}]','["",{"translate":"・%1$s魔石","with":[{"translate":"精霊の"}]},"\\\\n\\\\n",{"translate":"- 必要な魔石"},"\\\\n\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"元素の"}]},"\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"陰陽の"}]}]','["",{"translate":"・%1$s魔石","with":[{"translate":"神威の"}]},"\\\\n\\\\n",{"translate":"- 必要な魔石"},"\\\\n\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"賢者の"}]},"\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"純化の"}]}]','["",{"translate":"・%1$s魔石","with":[{"translate":"神秘の"}]},"\\\\n\\\\n",{"translate":"- 必要な魔石"},"\\\\n\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"精霊の"}]},"\\\\n",{"translate":"・%1$s魔石","with":[{"translate":"神威の"}]}]'],display:{Name:'{"translate":"合成の手引き","bold":true,"color":"yellow"}'}}

**Comment by Irohamaru** [comment]
item出力python v1.05に更新
