### ISSUE TITLE
[TODO] デバッグモード用難易度を追加

### ISSUE THREAD

**Issue by waxsd100** [TUSB/TheUnusualSkyBlock#140]
### 重要度

今すぐ

### このTODOはこのTUSB Versionに影響が出る

v13α

## 何故必要なのか?
1.  制作中に不意にギミックが作動して復旧する必要がある場所が出てくる
  1.1.  脅威島とかワールドにひどい影響を与えるギミックの対策にもなるし

## 何故必要なのか
1.  ギミック破損するためリリース遅延する
2.
3.

## 何故この重要度なのか
1.  v13αリリースまで対応必要なため

## いつまで対応が必要か
1.  リリースまでに対応

**Comment by waxsd100** [comment]
色はdark_gray

特殊なことをしないと出ないようにしたいんだけども、特殊なことは何をする？

**Comment by NePonpon** [comment]
> 色はdark_gray
> 
> 特殊なことをしないと出ないようにしたいんだけども、特殊なことは何をする？

プレイヤーが実行する必要がないからfunctionを手で実行する方法を考えている
`/function main:difficulty/select/debug`

**Comment by NePonpon** [comment]
ベースの難易度はカジュアルとするため、ほとんどの設定はカジュアルを引き継ぐ

ワールドへの影響は
* 通常世界 脅威島のギミック動作停止
* 自然湧き停止

が挙げられている

**Comment by NePonpon** [comment]
0e8c4bd8acd67923063e2ae1d8c7c0e3449e119a

**Comment by NePonpon** [comment]
特殊デバフ　呪詛
難易度デバッグの際にアイテムを落とさない
