### ISSUE TITLE
クラウディア入り口のVer表記の変更

### ISSUE THREAD

**Issue by EllaCoat** [TUSB/TheUnusualSkyBlock#141]
### 重要度

通常

### このTODOはこのTUSB Versionに影響が出る

v13α

## 何故必要なのか?
1. プレイする人たちにこのマップのバージョンがどのバージョンであるかをわかりやすくするため。

## 何故必要なのか
1. 島が１つしかないα版と通常世界が一通りプレイできるα2版は、異なるバージョンであるため正確な表記が必要。

## いつまで対応が必要か
1. リリース直前までに

**Comment by NePonpon** [comment]
![image](https://github.com/TUSB/TheUnusualSkyBlock/assets/62683212/4bf6ee7b-e3b6-4a5f-8fac-451ff5cc41a0)

このようにver表記の変更がされた。
