### ISSUE TITLE
[TODO] (きらめく)ヒツジンさん の Team問題

### ISSUE THREAD

**Issue by aatomu** [TUSB/TheUnusualSkyBlock#142]
### 重要度

低め

### このTODOはこのTUSB Versionに影響が出る

v13α

## 何故必要なのか?
1. Team名:""は存在しないのでWarnを吐く

## 何故必要なのか
1. エラーメッセージを大量に吐いて鯖に負荷がかかる

**Comment by aatomu** [comment]
Fixed: #0e4ae2c

**Comment by NePonpon** [comment]
0e4ae2c
e8c3e8e
