### ISSUE TITLE
[TODO] ポーション管理TUSBメモリーの作成

### ISSUE THREAD

**Issue by NePonpon** [TUSB/TheUnusualSkyBlock#147]
### 重要度

低め

### このTODOはこのTUSB Versionに影響が出る

v13 Release

## 何故必要なのか?
1. ポーション一つ一つにTUSBメモリーを追加していくと面倒
2. 一元管理できると修正などが楽
3.

## 何故必要なのか
1. 使用頻度が低いのにデータが存在する状態になるので、削減できるなら削減したい
2.
3.

  

## 何故この重要度なのか
1. 
2. 
3. 

## いつまで対応が必要か
1. 
2. 
3.

**Comment by NePonpon** [comment]
`{Id:"",Duration:0,Amplifier:0b,ShowParticles:true}`
と非常にマクロ向きのNBTをしているのでマクロ追加後に実装予定

Durationが-1のときにinfiniteに置換する必要がある。

**Comment by NePonpon** [comment]
「汎用魔法薬」というTUSBメモリーをシートに登録した

**Comment by anminmakura** [comment]
これに関しては制作する可能性があるので再開。
