### ISSUE TITLE
建築鯖を1.16にする

### ISSUE THREAD

**Issue by uran247** [TUSB/TheUnusualSkyBlock#15]
- [x] 1.16.4の正式リリースを待つ
- [x] spigotビルド
- [x] NFSにディレクトリ作成
- [x] 建築データ移動
- [x] 新ディメンションマージ
- [ ] 起動スクリプト修正
- [ ] 起動
- [ ] 動作チェック

**Comment by NePonpon** [comment]
現在1.16.4で建築鯖が作動していて、このissueの目的達成しているのでclose
