### ISSUE TITLE
特殊装備枠のアイテムをメインまたはオフハンドに持った際に、スニークするとスキルが誤発動してしまう

### ISSUE THREAD

**Issue by EllaCoat** [TUSB/TheUnusualSkyBlock#150]
### 重要度

通常

### このTODOはこのTUSB Versionに影響が出る

v13α

## バグ詳細
特殊装備枠、例えば召喚士の魂や水を持った状態でスニークするとそれらに登録されているスキルが誤発動してしまう

## 何故必要なのか?
そもそも想定した挙動ではないため

## 何故必要なのか
意図してない効果を持つ道具として扱われてしまう可能性が高い

**Comment by NePonpon** [comment]
issue名が途切れている。および本文不足によりどのような問題かわからない
@EllaCoat 追記お願い

**Comment by NePonpon** [comment]
![image](https://github.com/TUSB/TheUnusualSkyBlock/assets/62683212/627f3dbd-3fc1-410b-b7c9-9b4f8675f197)
![image](https://github.com/TUSB/TheUnusualSkyBlock/assets/62683212/f3a9df1a-d90f-4029-a85a-a07fb2677bc8)

これらのアイテムが特殊装備枠で、頭に装備していなければ発動しないのが想定みたい

**Comment by NePonpon** [comment]
スニークする。だからどこに持っててもよくない？とは思うけど
手に持ってスニーク or 装備してスニーク という発動条件なら別けられるべきと思ってる

**Comment by aatomu** [comment]
仕様としてClose
