### ISSUE TITLE
釣りで何も釣れないことがある

### ISSUE THREAD

**Issue by Suyarumi** [TUSB/TheUnusualSkyBlock#152]
### 重要度

低め

### このTODOはこのTUSB Versionに影響が出る

v13α

### タスク内容

通常世界で釣りをしたときに何も釣れないことがある。
## 何故必要なのか?
1. 釣っても何も釣れないのはマイクラにおいて不自然な動作である。

### 予想される問題

挙動に違和感が少し出る。
## 何故必要なのか
1.特別に必要というわけではない。

  

## 何故この重要度なのか
1. 特別に重要というわけではない

## いつまで対応が必要か
1. 最悪修正しなくても良い

**Comment by NePonpon** [comment]
#179 が同じ問題で、より詳しい情報が載っている。
そのため、このissueを重複としてcloseする。
