### ISSUE TITLE
自然湧きを動的にする。

### ISSUE THREAD

**Issue by Suyarumi** [TUSB/TheUnusualSkyBlock#160]
### アイデアのカテゴリー

Mob

### アイデア概要

- 自然湧きのレベルがランダムに上昇するようにする。
- - 上昇量の幅は攻略率か何かに依存させる。
- - 稀にLvが100を超えた異常な強さを持つモブがスポーンするようにする。
- - レベルが上昇した敵はドロップがよくなるように設定する。
- 攻略が進めば進むほど強い敵が自然湧きするようにする。
- 攻略が進めば進むほど自然湧きで一度に湧いてくる敵の量を増やす

### 実現方法

1. レベルの上昇は"enemy:natural_spawn"に上昇処理を挟むことで実現する。
    1. レベルに応じてドロップを良くする方法については実現方法は特に浮かんでいない。
2. 自然湧きが攻略度に応じて変化するようにするために、自然湧きのloottableにweightの他にqualityを追加するように自然湧き管理シートと出力用pythonコードを修正する。
3. レベルに応じてドロップを良くするためにはInitialize処理に自然湧きの場合にはloot_tableのcountをスポーンさせるモブに応じて変更するように修正する。

### なぜこの提案をしたか
シングルプレイでTUSB v13 α2をプレイしていて自然湧きに変化がないのに飽きを感じたから。
~~もっと強い敵が出て欲しいから。~~
序盤は十分強いと感じるが、装備が整ってレベルも上がった頃になると物足りなくなったから。

**Comment by anminmakura** [comment]
Lvの上がった自然湧きは名前の前に☆とか記号が付くと良いかもしれないというアイディアを書いてみる。

**Comment by Suyarumi** [comment]
## 実装終了
https://github.com/TUSB/TheUnusualSkyBlock/commit/35c2517ac262eae4b8cb8dead395669c8139a119
https://github.com/TUSB/TheUnusualSkyBlock/commit/5efdc470974f118cbfb813cfd66fcc1706ccf988
https://github.com/TUSB/TheUnusualSkyBlock/commit/dd36cc2586b328bdc786096cb0a685ceb5239ad8
https://github.com/TUSB/TheUnusualSkyBlock/commit/700476d55a4c8790329df3bbe6de97b219f2235a
https://github.com/TUSB/TheUnusualSkyBlock/commit/0c97246239e0d0a61f081e506756d25e0d702ae3
## 実装したもの
- 自然湧きのレベルのランダム化
- 稀にレベルがとても上昇した敵がスポーンするように
- 攻略率に応じた自然湧きのドロップ増加
