### ISSUE TITLE
[要望] 色ガラスの使い道とエレメントと錬金窯(立体レシピ)と錬金エリア

### ISSUE THREAD

**Issue by anminmakura** [TUSB/TheUnusualSkyBlock#162]
### アイデアのカテゴリー

レシピ

### アイデア概要

色ガラスは現状チェストの飾りつけにしか使用していなく、また利用もされなく余らせてしまっているのを見て思いついた。
まず色ガラスを取引材料とするエレメントを売る固定商人を作成し、エレメントを交換できるようにする。
エレメントは錬金窯で使用する事が出来、最大でエレメントを５つ使用できる(ホッパのGUIを使用)
エレメントは錬金エリアでプレイヤーで移動できる手段であり、例えば移動のエレメント(20歩)であれば20歩移動を行うことができる。
スキルのエレメント(1回)はスキルを実行でき、回避のエレメントはダメージを回避することができる等と
プレイヤーに移動や行動に制限をかし、移動少ない行動制限でいかに錬金エリアを探索することを目的としている。
錬金エリアのルールとしてダメージを受けたらすぐに戻されるというルールと
この錬金エリアは入るごとに中の報酬が復活し、プレイヤーは立体的な行動を行って
その報酬を取得するようにするというのが目的となっている。
このシステムのみそはエレメントを組み合わせによってエレメントを代用したり、職業によってルートが異なるという現システムとの連携を考えている。

### 実現方法

省略。

**Comment by anminmakura** [comment]
- 「色ガラス」は現在、チェストの飾りつけにしか使用されておらず、また余ってしまっていること
- 色ガラスを取引材料とするエレメントを売る固定商人を作成し、エレメントを交換できるようにする。
- エレメントは錬金窯で使用でき、最大で5つまで使用できます（ホッパのGUIを使用）
- エレメントは錬金エリアでプレイヤーが移動するための手段であり、例えば移動のエレメント（20歩）であれば20歩移動することができる。
- スキルのエレメント（1回）はスキルを実行でき、回避のエレメントはダメージを回避することができる。
- これにより、プレイヤーに移動や行動に制限をかけ、移動を少なくすることで錬金エリアを探索することを目的。
- 錬金エリアのルールとして、ダメージを受けた場合はすぐに戻されるというルールがある。
- また、この錬金エリアは入るたびに中の報酬が復活し、プレイヤーは立体的な行動を行ってその報酬を取得するようにすることが目的。
- このシステムの魅力は、エレメントを組み合わせることでエレメントを代用したり、職業によってルートが異なる。

**Comment by waxsd100** [comment]
このissueの中に要望が3つはいっていて、それぞれについての内容に議論できない

・色ガラスの使い道の追加
・新エリア(錬金エリア)の追加
・ミニゲーム(錬金エリアの探索)の追加

の3つでIssue作って欲しい。
その後この要望の内容はこれと関係あるよって感じで #162 みたいな感じでIssue番号指定して

理由:

1. もし、色ガラスだと全種類作成、入手できるかわからないから
別の素材で固定商人をやろうって話になった場合
・色ガラスの使い道の追加 
だけの問題だけ解決できないままになる。

2. 話を噛み砕くのと、巨大タスクだと作るときどこか中途半端になる可能性が出てくる。

**Comment by anminmakura** [comment]
了解。ちょっと要望を分けてみますー

**Comment by NePonpon** [comment]
> Tags「名称はPon氏が知っているだろうアレ」
これ草
そのNBTタグは`NoHold:true`

**Comment by anminmakura** [comment]
要望に色ガラスの使い道( #163 )を追加しました。  
新エリア(錬金エリア)とミニゲーム(錬金エリアの探索)の追加はほぼ同じ案なので総合( #164 )しました。
