### ISSUE TITLE
エンチャントの効果を説明する本を作る

### ISSUE THREAD

**Issue by EllaCoat** [TUSB/TheUnusualSkyBlock#167]
### アイデアのカテゴリー

アイテム・TUSBメモリー

### アイデア概要

それぞれの魔石が付与することのできるエンチャントの効果を説明している本を作って自然湧きの行商人に売らせる。

### アイデアの要望理由

・魔石に関してはあまりにも種類が多すぎるため、チュートリアルで説明しただけでは不十分だと思われるため
・アイテムさえ手に入れられれば、魔石の効果がわからなくなった時に辞書感覚で調べるようにできれば、魔石に対するプレイヤーの理解度も上げられると思われるため

**Comment by NePonpon** [comment]
* エンチャント辞典
https://github.com/TUSB/TheUnusualSkyBlock/blob/ca51db403676ec8f9790e328a50c591c036c7917/data/item/loot_tables/item/written_book/enchant_book.json
* 【行商】商業ゴブリン・メタルティンカ https://github.com/TUSB/TheUnusualSkyBlock/blob/ca51db403676ec8f9790e328a50c591c036c7917/data/settings/functions/enemy/global/neutrality/shoot/goblin_merchant_metaltinka/main_b.mcfunction

**Comment by NePonpon** [comment]
エンチャント辞典は翻訳のために再編集する必要がある。
