### ISSUE TITLE
[バグ] 釣りでトラップアイテムを釣り上げた時、ブロックに埋まっていたらモブが召喚されない

### ISSUE THREAD

**Issue by NePonpon** [TUSB/TheUnusualSkyBlock#179]
### 発生したTUSBv13のVersion

v13.0.0α2

### 概要

釣りでトラップアイテムを釣り上げた時に、アイテムがブロックに埋まっていたらモブが召喚されない。
これによって、放置して釣りをすることが可能となる。

ブロックに埋まったらという条件は結構ゆるく、釣り針が水流で流れて壁にくっつくだけでトラップアイテムが機能しなくなる。

### 再現方法

1. 水源の中にフェンスを設置する
2. フェンスに向かって釣り針を垂らす
3. トラップアイテムを釣り上げる
	ただし、Mobが召喚されないため意図して再現環境を整えないとバグの再現確認は難しい。

### 予想される動作

どんな状況でもトラップが機能する。

**Comment by NePonpon** [comment]
再現に役立つルートテーブル

`minecraft:gameplay/fishing`
```json
{
  "pools": [
    {
      "rolls": 1,
      "entries": [
        {
          "type": "minecraft:loot_table",
          "name": "item:item/firework_star/etc/trap_spawn_02woolscaffold"
        }
      ]
    }
  ]
}
```
釣り上げると必ず銀羊のトラップアイテムが出る。

**Comment by Suyarumi** [comment]
関連するIssue
https://github.com/TUSB/TheUnusualSkyBlock/issues/152

**Comment by NePonpon** [comment]
修正めどが立たないので、既知の問題として扱う

**Comment by NePonpon** [comment]
#174
これを完了でこちらも修正される

**Comment by NePonpon** [comment]
#473 と同時にクローズされるように紐づけた
