### ISSUE TITLE
[バグ] 刻印やTUSBメモリー等の大多数が動かない。

### ISSUE THREAD

**Issue by anminmakura** [TUSB/TheUnusualSkyBlock#198]
### 発生したTUSBv13のVersion

v13.1.0α2

### 概要

原因は主にコントロールエリアのシュルカーボックス等がワールド初入出時の初期化処理によって置かれないので全コマンドが機能不全を起こしている。

### 再現方法

全員起こるバグなので今すぐ修正するべき案件。

**Comment by NePonpon** [comment]
forceloadの強制読み込みは即時ではないため、1秒遅らせてからブロックを設置することで確実に設置するように変更
