### ISSUE TITLE
[要望] 交易島に飛空島初期ゲートを固定し、プレイヤーが飛空島に一度も侵入しない場合、飛空島の巡回フラグが成立しないようにしたい

### ISSUE THREAD

**Issue by anminmakura** [TUSB/TheUnusualSkyBlock#206]
### アイデアのカテゴリー

ギミック

### 以下が実行された時飛空島巡回フラグが立つ
- 正規の方法でプレイヤーが交易島内のゲートから飛空島に侵入する
- 上記のフラグが成立していない時、飛空島周回券のスキルを実行する

### アイデアの要望理由

初めに交易島内の飛空島ゲートが開いている状態にしたほうが
よりユーザーフレンドリーなレベルデザインになるはず。
今後の為に以下のように飛空島巡回フラグが成立するように改良案を提出したい。

**Comment by NePonpon** [comment]
load_onceで初回駅を決めるが、決めた後、scheduleを取り消す。
プレイヤーが通ったことを1度だけ検知する方法を検討する必要がある

**Comment by NePonpon** [comment]
別の案として、監獄の島を最初の駅とする案があった。これだと、プレイして1日後(20分後)に交易島に到着する感じ。
ただ、手慣れたプレイヤーが最速で飛空島へ行けない問題や「ビーコンを目印にしてね」ということができなくなる
