### ISSUE TITLE
[バグ] 飛空島の道場の報酬エリアにエンダーパールで侵入することができる

### ISSUE THREAD

**Issue by EllaCoat** [TUSB/TheUnusualSkyBlock#249]
### 発生したTUSBv13のVersion

v13.1.2α2

### 概要

岩盤によるガードがないためエンダーパールののめり込みで飛空島の道場の報酬エリアに侵入できてしまう。

### 再現方法

1.エンダーパールを持っていく
2.クリア時に開かれるであろう壁にのめり込む
3.報酬エリアに入れてしまう

### 予想される動作

クリア時に開かれる壁に岩盤を敷くことで進入不可の状態にすべき

**Comment by NePonpon** [comment]
エンダーパールめり込み抑制システムを実装したため解決されたと考えられる。
