### ISSUE TITLE
[要望] ショートカットメニューの「編集モード」と「スキル付与モード」等の枠のパーティクルの色は別にする

### ISSUE THREAD

**Issue by anminmakura** [TUSB/TheUnusualSkyBlock#253]
### アイデアのカテゴリー

インターフェイス全般

### アイデア概要

編集モードの枠「赤紫」
スキル付与モードの枠「オレンジ」
バーストゲージの枠「黄色」

### アイデアの要望理由

編集モードのオレンジの枠を赤紫の枠にすると編集モードと一目でわかるのではないかと思いました。

**Comment by NePonpon** [comment]
バーストブレイク
* ON (白)
#FFFFFF
1 1 1
* OFF (黄)
#FFF450
1 0.96 0.31

![image](https://github.com/TUSB/TheUnusualSkyBlock/assets/62683212/33d64975-d8e1-4535-92eb-e6d13bdb897e)

**Comment by NePonpon** [comment]
どちらもこのように変更しますね
