### ISSUE TITLE
[バグ] <足元にブロックがある場合、フィールで羊毛が正しく設置されない場合がある>

### ISSUE THREAD

**Issue by Suyarumi** [TUSB/TheUnusualSkyBlock#265]
### 発生したTUSBv13のVersion

v13.1.2α2

### 概要

足元になにがしかのブロックがある場合、フィールで設置される羊毛が正方形にならない
https://discord.com/channels/290014442748379137/1218841924434268160/1218841924434268160

### 再現方法

![2024-03-17_18 55 33](https://github.com/TUSB/TheUnusualSkyBlock/assets/43696755/9f13fec5-fe24-4eab-a94e-1130f762104c)
このようにブロックを配置し、エンドストーンレンガの上でフィールを発動する。
そのさい、フィールの範囲は9×9に設定しておく。

### 予想される動作

9×9全てがしっかり埋め立てられる

### 原因となるコマンド

```mcfunction
skill:act/summoner/fill/level9
```

**Comment by NePonpon** [comment]
中央から周囲へ展開されているイメージの動作をしている

v12でも判定位置は違うが同じような仕様が残っている。
そのためv13でのこの動作も仕様とする
