### ISSUE TITLE
[バグ] フレンド・ウルフ+つんつんの音量が大きすぎる

### ISSUE THREAD

**Issue by yabane** [TUSB/TheUnusualSkyBlock#266]
### 発生したTUSBv13のVersion

v13.2.0α2

### 概要

召喚したフレンド・ウルフにつんつんを使用した上で壁に当たった場合に発生する、爆発のような音が非常に大きい
特に閉所では多く鳴り、体感雷メイジといい勝負かそれより大きいくらいです

### 再現方法

1.サモンP:ウルフを使用する
2.つんつんを使用する

**Comment by anminmakura** [comment]
アレはバグじゃなくて**仕様**ですね。**雷エンティティ呼び出し時の効果音**なので。
その音をコントロールする場合、雷エンティティの呼び出しをせず雷を他の表現で再現しなければなりません。
製作コストを考えるとアレが現状のベストであり、妥協点でもあります。
しいて言うならオオカミの遠吠えの効果音を小さくする程度でしょうか？
