### ISSUE TITLE
[バグ]  オイルドラムのデスログに誤字がある

### ISSUE THREAD

**Issue by yabane** [TUSB/TheUnusualSkyBlock#276]
### 発生したTUSBv13のVersion

v13.2.0α2

### 概要

オイルドラムの爆発に巻き込まれ頭皮に「致命的を負った」となっている

### 再現方法

オイルドラムのデスログ

**Comment by NePonpon** [comment]
https://github.com/TUSB/TheUnusualSkyBlock/commit/c6590adfa5c28ddc66b2a16c072e089f2a062074
