### ISSUE TITLE
[要望] 白魔導士のセイクリッドピラー強化案

### ISSUE THREAD

**Issue by anminmakura** [TUSB/TheUnusualSkyBlock#279]
### アイデアのカテゴリー

職業スキル

### アイデア概要

現状は**実行時現在の最大体力の減少量によってダメージが増減する**ようになっているが、
改善案として**現在の最大体力増加量(金ハート含)を参照し、ダメージを増減する**ようにし、
また**実行時全回復を行うのではなく、逆に使用すると現在の最大体力の25%の割合ダメージを
受けるようにする**ことでケアル等の即時回復スキルが活かされるようになる。

さらにセイクリッドピラーのダメージ範囲も1.5倍程調整し、敵モブに当たりやすくする事で
セイクリッドピラーの使い勝手も向上し、かつダメージソースとしての立ち位置が確保されようになる。

### アイデアの要望理由

現状のホーリーの次にダメージソースになるであろうセイクリッドピラーがあまりにも弱すぎると思ったので強化案を提示したかった。

**Comment by NePonpon** [comment]
61627726a7d3c330bec0cc819dd078c0e3eaf44a...546943627512eeb1318f960a6413d68b27f909a0

**Comment by NePonpon** [comment]
[b9d2e03](https://github.com/TUSB/TheUnusualSkyBlock/commit/b9d2e033160cd33600eee8a9506ab7ffaad806f3)
