### ISSUE TITLE
[要望] ホーリーが弱い弱いと言われているので強化案を出してみる

### ISSUE THREAD

**Issue by anminmakura** [TUSB/TheUnusualSkyBlock#280]
### アイデアのカテゴリー

職業スキル

### アイデア概要

ホーリーの弾をバウンドするようにし、跳弾して多段ヒットしやすくするようにすれば
尖ったスキルになるのではないかと妙案を思いついた。
現状弾が跳弾するようなスキルは存在しないので、個性が出て良い方向に転がるかもしれない。
また敵に攻撃を与えた時、全属性ダメージを与える以外に敵の魔法防御を下げるといった
追加効果も入れても良いかもしれない。

### アイデアの要望理由

弱い弱いと言われているので...w

**Comment by NePonpon** [comment]
ホーリー追尾弾にしたんだったよね

**Comment by NePonpon** [comment]
1d947007545e9a7fd8a8a33b598f5c76bad3b57c

速度を落とし追尾弾にすることで総ダメージ量を増加させる弾に変更
