### ISSUE TITLE
[要望] アイテムの初期設定で付与されている刻印とは別に「魔石による強化」を別枠の強化として再設定する

### ISSUE THREAD

**Issue by anminmakura** [TUSB/TheUnusualSkyBlock#328]
### アイデアのカテゴリー

アイテム・TUSBメモリー

### 魔石でしか強化できない刻印
- 属性ブースト系
- 特定のデバフ無効
- 波動
- 魔法属性系の軽減

### 魔石には付与できない刻印
- HP吸収
- MP吸収
- 氷渡り
- 防御系
- HP増加
- MP増加

### アイデアの要望理由

現在、アイテムには以下の3つの能力が設定できるようになっています。
1. アイテム自身の素の能力（Modifier）
2. 最初から付与されている刻印
3. TUSBメモリーでのスキル付与

刻印がない場合、後から魔石を使って刻印を付与することが可能です。

しかし、この仕様では魔石の価値が低下し、多くのプレイヤーが魔石を収集・整理しなくなっています。

この問題を解決するために、最初から刻印が付与されているアイテムでも、魔石による強化を別枠として設定し、
さらに魔石でしか付与できない特殊な能力を追加する提案をしました。
これにより、魔石の利用価値が向上すると考えています。

【追記】
また既存のModifierと刻印で効果が被り、また名前が異なるものもある為、
プレイヤーが混乱する原因の１つとなっています。

以下は、新しい仕様に基づいた能力です。

~~1. アイテム自身の素の能力（Modifier）~~
見づらく、調整や管理が難解な為、今後はModifierを廃止し、2に統合予定

2. 最初から付与されている刻印
任意で複数付与する事が出来、Modifier系の刻印も設定可

3. TUSBメモリーでのスキル付与

4. 魔石でしか付与できない特殊な能力（新機能）
今まで通りプレイヤーが魔石を付与する事でランダムエンチャントが付与される

**Comment by anminmakura** [comment]
アイテム自身の素の能力（Modifier）は廃止し、元々のエンチャント内容を指定できるように変更して  
全てエンチャントで統一する方がシステム的に最適かも。ちょっとこの案をもうひと捻りしてみる。

**Comment by waxsd100** [comment]
> [!NOTE]
> 要望ラベルは実装必須の**機能追加**と実装必須ではない**アイデア**が混在しているため非推奨ラベルです。
> 機能追加(実装確定)なら`機能追加`ラベル
> アイデア(要望や実装未確定)なら`アイデア`ラベル
> を追加し、`要望`ラベルは削除してください。

**Comment by anminmakura** [comment]
現行案とはかけ買慣れた古い案である為却下タグを付与。
