### ISSUE TITLE
[要望] マイナス系の刻印の追加

### ISSUE THREAD

**Issue by anminmakura** [TUSB/TheUnusualSkyBlock#332]
### アイデアのカテゴリー

刻印

### アイデア概要

マイナス刻印の案

- ライフロス
アイテムの種類：防具・盾
現在の体力が割合で減少

Tier | 効果量
-- | --
1 | -5%
2 | -15%
3 | -30%
4 | -45%
5 | -50%
6 | -65%
7 | -80%
8 | -95%

- マナロス
現在のマナが減少
アイテムの種類：防具・盾

Tier | 効果値
-- | --
1 | -50
2 | -100
3 | -150
4 | -200
5 | -250
6 | -300
7 | -350
8 | -400

- ノックバックロス
アイテムの種類：全て
現在のノックバックが割合で減少

Tier | 効果量
-- | --
1 | -5%
2 | -15%
3 | -30%
4 | -45%
5 | -50%
6 | -65%
7 | -80%
8 | -100%

- スピードロス
アイテムの種類：全て
現在の移動速度が割合で減少

Tier | 効果量
-- | --
1 | -5%
2 | -15%
3 | -30%
4 | -45%
5 | -50%
6 | -65%
7 | -80%
8 | -100%

- 攻撃力減少
アイテムの種類：全て
現在の攻撃力が割合で減少

Tier | 効果量
-- | --
1 | -5%
2 | -15%
3 | -30%
4 | -45%
5 | -50%
6 | -65%
7 | -80%
8 | -100%

- 攻撃速度減少
アイテムの種類：全て
現在の攻撃速度が割合で減少

Tier | 効果量
-- | --
1 | -5%
2 | -15%
3 | -30%
4 | -45%
5 | -50%
6 | -65%
7 | -80%
8 | -100%

- 防御力減少
アイテムの種類：全て
現在の防御力が割合で減少

Tier | 効果量
-- | --
1 | -5%
2 | -15%
3 | -30%
4 | -45%
5 | -50%
6 | -65%
7 | -80%
8 | -100%

- 防具耐久減少
アイテムの種類：全て
現在の防具耐久が割合で減少

Tier | 効果量
-- | --
1 | -5%
2 | -15%
3 | -30%
4 | -45%
5 | -50%
6 | -65%
7 | -80%
8 | -100%

### アイデアの要望理由

#328 案に備え、今後Modifierでの制御が今後なくなるので、
マイナス系のModifierに代わるマイナス刻印を制作して
任意に付与または、魔石付与時にランダムに付与されるようにする。

**Comment by waxsd100** [comment]
> [!NOTE]
> 要望ラベルは実装必須の**機能追加**と実装必須ではない**アイデア**が混在しているため非推奨ラベルです。
> 機能追加(実装確定)なら`機能追加`ラベル
> アイデア(要望や実装未確定)なら`アイデア`ラベル
> を追加し、`要望`ラベルは削除してください。

**Comment by anminmakura** [comment]
マイナス系のエンチャントは需要があるが、本案は刻印としての案である為、
別でマイナスエンチャント案を作るべきだと判断した為却下タグを付与しました。
