### ISSUE TITLE
[要望] 各アイテムに刻印容量限界を設定しプラス、マイナス刻印で容量を調整して刻印付与が可能かどうかを決定する

### ISSUE THREAD

**Issue by anminmakura** [TUSB/TheUnusualSkyBlock#333]
### アイデアのカテゴリー

刻印

### アイデア概要

例として、「エンド・オブ・エンド 刻印容量：10」というアイテムがあるとします。

このアイテムには、すでに以下の刻印が付与されています。
- 攻撃力Ⅳ (+4)
- 攻撃速度減少Ⅱ (-2)
- マナⅠ (+1)

これらの刻印を合計すると、基礎刻印容量は 3 になります。

- +4（攻撃力） - 2（攻撃速度減少） + 1（マナ） = 3

このアイテムの最大刻印容量は10なので、残りの刻印容量は 7 です。

- 10（最大容量） - 3（基礎刻印容量） = 7

この残りの容量（7）を使って、好きな刻印を付与することができます。
ただし、容量を超えないように注意する必要があります。

例えば、攻撃力Ⅷ (+8) のような刻印は容量を超えてしまうので付けられませんが、
攻撃力Ⅶ (+7) なら付けられます。また、以下のように刻印を組み合わせることも可能です。

- 攻撃速度増加Ⅱ (+2) + 攻撃力Ⅴ (+5) = 7

逆に、マイナスの効果を持つ刻印を付けることで、容量を増やすこともできます。
例えば、マナロスⅠ (-1) を付与すると容量が1増え、合計容量が 8 になります。
この状態で攻撃力Ⅷ (+8) を付けることができます。

### アイデアの要望理由

現状の刻印は一度付与したらそれ以上は付与できない為、プレイヤーが装備の試行回数を積みにくい。
また予定としてv13βでは魔石の報酬はチェスト報酬のみとなる為、以前のように気軽に付与がしずらくなる。

その為、プレイヤーがアイテムの容量を見つつ後から刻印を付与して調整可能にする。
これにより戦略性がさらに増し、１つのオリジナル武器を作成がしやすくし、制作側の調整コストを抑えられる。

**Comment by anminmakura** [comment]
追記：マイナス刻印の上限は刻印容量分の値と対となるほうが歯止めになるようにする。

例：エンド・オブ・エンド 刻印容量：10 であれば、エンド・オブ・エンド 刻印マイナス刻印容量：10となる(-10～10)
これにより無茶苦茶なマイナスを付与し、結果どんなアイテムでもとんでもない刻印容量になることはなくなる。
(これの欠点としてプレイヤーがいちいち計算をしなければならなくなるので、この辺りも今後何とかできればと思っている)

**Comment by waxsd100** [comment]
> [!NOTE]
> 要望ラベルは実装必須の**機能追加**と実装必須ではない**アイデア**が混在しているため非推奨ラベルです。
> 機能追加(実装確定)なら`機能追加`ラベル
> アイデア(要望や実装未確定)なら`アイデア`ラベル
> を追加し、`要望`ラベルは削除してください。

**Comment by anminmakura** [comment]
現状のエンチャントシステムは刻印を使用せず、バニラのエンチャント台のシステムを使用する方式となった為、
却下タグを付与しました。
