### ISSUE TITLE
[要望] スキル及び刻印等に「風属性」の概念を追加する

### ISSUE THREAD

**Issue by anminmakura** [TUSB/TheUnusualSkyBlock#335]
### アイデアのカテゴリー

属性

## 追加される刻印
- 風ダメージ追加
- ウィンドブースト

## スキル
風属性が追加されると、以下のスキルを風属性に変更または追加を行う。<br>
これにより黒魔導士、召喚士等にありがちなスキル属性の偏りが若干解消されるかもしれない。

### 剣士
- 真空斬り<br>
「狙った敵をカマイタチで切り裂く」と説明されているので、魔石で付与された属性によって属性を変えるのではなく、風属性に変更が妥当。

### 忍者
- 一閃<br>
「周囲にかまいたちを発生させながら突進する。」と説明されているので、雷属性のダメージではなく、雷、風属性に変更が妥当。

### 狩人
- バードストライク<br>
「竜巻を発生させ、敵を落下させる。浮遊している敵には大ダメージ。」と説明されているので、無属性ではなく、風属性に変更が妥当。

### 白魔導士
- ホーリー<br>
物理属性及び闇以外の全属性が付与されているスキルなので新たに風を追加し、炎、氷、雷、風、光属性に変更が妥当。

### アイデアの要望理由

現行の職業スキルには、炎、氷、雷、光、闇の5属性以外の概念を
無理やりこの5属性のいずれかに割り当てているものが複数存在しています。
(上記の概要参照)

特に風属性にはこのような問題が多く見られ、
これを機に新しく風属性を追加したいと考えています。

また、Minecraft 1.21には風のモンスターであるブリーズが存在しており、
風属性の追加は今後の課題として重要であると考えました。

**Comment by anminmakura** [comment]
今後属性ダメージは
物理、魔法、理外の３つとなるので
ダメージとして見るのではなくどのようなデバフを入れるかとして見る

**Comment by waxsd100** [comment]
> [!NOTE]
> 要望ラベルは実装必須の**機能追加**と実装必須ではない**アイデア**が混在しているため非推奨ラベルです。
> 機能追加(実装確定)なら`機能追加`ラベル
> アイデア(要望や実装未確定)なら`アイデア`ラベル
> を追加し、`要望`ラベルは削除してください。

**Comment by anminmakura** [comment]
現行の案では、
炎、氷、雷、光、闇の5属性のダメージ値概念は廃止※され、
物理、魔法、理外のダメージ概念値に書き換わる為、風属性を追加されることはない為却下タグを付与しました。

※5属性特殊デバフはそのまま。
また風属性のデバフは病気という尤もらしいものがあるので今後風属性デバフを入れるかは
審議の必要がある。
