### ISSUE TITLE
[TODO] SmartMotionのブロックタグの更新

### ISSUE THREAD

**Issue by anminmakura** [TUSB/TheUnusualSkyBlock#342]
### 重要度

通常

### このTODOはこのTUSB Versionに影響が出る

v13.3.0α

### タスク内容

SmartMotionにおけるブロック判定をまとめる以外に、
サイズとか当たり判定の有無で分類を行う必要がある。
実質編集しなくちゃいけないのは、full_block (フルブロックの列挙)と no_collision (当たり判定が無のブロックの列挙)
```
data/smart_motion/tags/blocks/full_block.json
```
```
data/smart_motion/tags/blocks/no_collision.json
```

## 解決策

```
assets/minecraft/model/block/*.json
```
を参照後、cmdプロンプトで
```
dir /b | clip
```
を実行しクリップボード貼り付けを行い、フォルダー内の名前を参照する。

## 何故必要なのか
SmartMotionが正常に動かなければモブや弾の特殊移動をさせることが出来なくなる。

## 何故この重要度なのか
今後必ず修正する必要があるが、現状モブ自体まだまだ制作できる段階ではない為

## いつまで対応が必要か
モブが作られ始める前には更新が必須

**Comment by NePonpon** [comment]
#187 と重複
