### ISSUE TITLE
全エリアの1.16ブロック化

### ISSUE THREAD

**Issue by anminmakura** [TUSB/TheUnusualSkyBlock#41]
**1.16になった際の現行ブロックの置き換え作業について**
- [x] 20%
- [x] 40%
- [x] 60%
- [x] 80%
- [x] 100%
- 要望
全エリアにて1.16で使えるようになったブロックを
そのエリアにあった素材に変換、設置、建築の追加を行っていく。

**Comment by NePonpon** [comment]
置き換え作業100%完了しているみたいなのでclose
