### ISSUE TITLE
summon armor_stand の呼び出しにて、MOBのAI付与時に別のAIを付与されてしまう

### ISSUE THREAD

**Issue by anminmakura** [TUSB/TheUnusualSkyBlock#63]
リピートコマンドを用いたり、高速で大量に召喚すると、Entityに本来付与したいAIが付与されない問題。

summon armor_standの召喚プロセスに何かしら問題があるのは明らかだが、
問題が起こる際、大量のログが出るので問題となるプロセスを見つけることが困難である。

現状の対抗できる手段としては

最終手段にAI側がEntityにAIを付与する際、AI自身がEntityの名前またはEntityのIdを取得し、
【Entity側】と【AI側】とで情報にずれが生じた場合、
AI側がKillを使用しバグったMOBを消し、自己消滅をするという手段が有力(？)

**Comment by anminmakura** [comment]
またこの問題の発生時、Passengersのシステムを用いたMOBに
AECが騎乗している場合以下画像のようにAECが残ってしまう。


![2022-01-16_22 (1)](https://user-images.githubusercontent.com/39670701/149688285-ae16ecc5-ebd3-4522-b05e-c4c981c4a124.png)
![2022-01-16_22](https://user-images.githubusercontent.com/39670701/149688302-7160185a-c48c-4152-a619-dd681e8be45a.png)


現状AEC以外のPassengers、、単体でのEntityでこの問題が起こるのかは現在調査中。

**Comment by NePonpon** [comment]
[`bug#63`](https://github.com/TUSB/TheUnusualSkyBlock/tree/bug%2363)ブランチを作成。

# 追加したもの
> [enemy:spawn/apply_status/mob](https://github.com/TUSB/TheUnusualSkyBlock/blob/aba858498017c2e0bc049dedbe3d3bbc9cb4723b/data/enemy/functions/spawn/apply_status/.mcfunction#L5)
```
 5| tellraw @a ["[enemy:spawn/apply_status/] ",{"selector":"@s"},"  ",{"entity":"@s","nbt":"TicksFrozen"}]
```

> [enemy:spawn/set_spawner/each_mob](https://github.com/TUSB/TheUnusualSkyBlock/blob/aba858498017c2e0bc049dedbe3d3bbc9cb4723b/data/enemy/functions/spawn/set_spawner/each_mob.mcfunction#L47)
```
47| tellraw @a ["[enemy:spawn/set_spawner/each_mob] ",{"nbt":"SpawnData.TicksFrozen","storage":"tusb_mob:"},"  ",{"nbt":"SpawnData.id","storage":"tusb_mob:"}]
```

> [main:tick](https://github.com/TUSB/TheUnusualSkyBlock/blob/aba858498017c2e0bc049dedbe3d3bbc9cb4723b/data/main/functions/tick.mcfunction#L5-L6)
```
 5| # tick正常終了エラー
 6| scoreboard players set $error _ -1
...
42| # tick正常終了エラー
43| scoreboard players reset $error _
```

* スポナーを作成するときに、作成されているMobのidとAI保存先OhMyDatIDを表示  
* Initialize処理をしているMobの名前と呼び出し先OhMyDatID表示  
* tickの処理が正常終了しているかのチェック 

### tick正常終了チェック
main:ticが最後まで実行されなかった場合、スコア`$error _`が-1に設定される。  
これをコマンドブロックで取得することでエラーをキャッチできる。
```
execute if score $error _ matches -1 run tellraw @a {"text":"[errpr] tickが正常に終了していません","color":"red","bold":true}
```
のコマンドをリピートコマンドブロックで実行し続ける。  
もしtickが正常終了しなかった場合、エラーがログに表示される。

# 仕組み理解
通常、Mobを召喚したとき以下のログが出力される。必要なもののみを抜粋している。  
> 例：ハートスケルトン
```
[enemy:spawn/set_spawner/each_mob] 34340  minecraft:area_effect_cloud
[enemy:spawn/set_spawner/each_mob] 34340  minecraft:skeleton
[enemy:spawn/apply_status/] ハートスケルトン  34340
[enemy:spawn/apply_status/] エリアエフェクトクラウド  34340
```
area_effect_cloud -> skeleton の順番でスポナーが作成されていき、  
ハートスケルトン -> エリアエフェクトクラウドの順番でAIが付与されていることがわかる。  
**スポナー作成をした1tick後にAIが付与されることに注意。**

上のログからはハートスケルトン及びAECに適用されるAIが保存されているOhMyDatIDは`34340`であることがわかる。
MobのAIは`DelayedDataList`に順番に保存されている。
保存はListにappend、読み込みは[-1]参照をするため、上のログから
```
DelayedDataList[{<AECのAI>},{<スケルトンのAI>}]
```
と保存されて、読み込みされることがわかる。

# バグ発生時の報告
AECが残るバグを確認した場合、これ以上ログが流れないようにする。  
AECに対して、
```
scoreboard players get <バグで残ったAEC> OhMyDatID
```
を実行し、バグが発生したAECのOhMyDatIDを取得する。  
ログを確認し、該当するOhMyDatIDのスポナー作成、AI付与が正常に行われているかどうか確認する。  
もし順番が間違っていたり、付与されるはずのエンティティがいない場合は報告をすること。

**Comment by NePonpon** [comment]
自身のOhMyDatIDを表示するように変更

**Comment by NePonpon** [comment]
# 原因
Mobの遅延ステータスが保存されたOhMyDatIDと紐づいているエンティティが、遅延ステータスをMobに適用する前にkillされてしまい、必要なOhMyDatIDがリリースされてしまうから。

## 検証ログ

```
[13:05:05] [Render thread/INFO]: [CHAT] [enemy:spawn/set_spawner/each_mob] 49152  minecraft:area_effect_cloud
[13:05:05] [Render thread/INFO]: [CHAT] [enemy:spawn/set_spawner/each_mob] 49152  minecraft:zombie
[13:05:05] [Render thread/INFO]: [CHAT] end_spawner_OMD: 49152
[13:05:05] [Render thread/INFO]: [CHAT] [enemy:spawn/set_spawner/each_mob] 16384  minecraft:area_effect_cloud
[13:05:05] [Render thread/INFO]: [CHAT] [enemy:spawn/set_spawner/each_mob] 16384  minecraft:zombie
[13:05:05] [Render thread/INFO]: [CHAT] 不要なOMDを削除したで！: 49152
[13:05:05] [Render thread/INFO]: [CHAT] [enemy:spawn/apply_status/] ハートゾンビ Lv1  読み込みOMD:49152  自分のOMD:24576
[13:05:05] [Render thread/INFO]: [CHAT] [enemy:spawn/apply_status/] エリアエフェクトクラウド  読み込みOMD:49152  自分のOMD:49152
```

* [enemy:spawn/set_spawner/each_mob] ...  
settingsのMob設定ファイルから読み込まれているエンティティIDと、遅延ステータスを保存するOhMyDatID

* end_spawner_OMD ...  
killされたスポナーが持っているOhMyDatID。  
このスポナーのOhMyDatには1tick前に読み込まれたMobの遅延ステータスが入っている。

* 不要なOMDを削除したで！ ...  
`oh_my_dat:sys/gc_loop`で不必要と判断されリリースされたOhMyDatID

* [enemy:spawn/apply_status/] ...  
遅延ステータスを適用するMobの名前、遅延ステータス読み込み元のOhMyDatID、Mob自身のOhMyDatID

## ログから読める情報
`49152`のOhMyDatに遅延ステータスを保存したが、`49152`のIDを持つスポナーが遅延ステータス読み込み前にkillされてしまった。  
その後、`oh_my_dat:please`が1回以上呼び出されることによってOhMyDatのシステムに`49152`のデータは不要と判断されたため
削除される。  
いざ遅延ステータスを読み込もうと`49152`のデータを呼び出しても、すでに削除済みのため正常なデータを適用できない。

### OhMyDatの補足
`oh_my_dat: id`に使用されているOhMyDatのidが記録されている。  
`oh_my_dat:please`が実行されて新たにIDが振り分けられるとき、ストレージに保存されているidと存在しているエンティティのIDを比較して、IDを持っていたエンティティがいない場合に可能な限りストレージを削除する。

# 修正方法
現在、Initialize処理前にスポナーのkillを実行しているため、OhMyDatの自動削除が実行される場合が起こってしまう。  
修正方法として、Initialize処理の終了後にkillするとOhMyDatの自動削除が実行されることがなくなる。
